---
name: Reusable Dev Files Cleanup

on:
  workflow_call:
    inputs:
      target_branches:
        description: 'Comma-separated list of branches to clean (e.g., main,master,development)'
        required: false
        default: 'main,master,development'
        type: string
      additional_patterns:
        description: 'Additional file patterns to remove (comma-separated)'
        required: false
        default: ''
        type: string
      skip_comment:
        description: 'Skip adding cleanup comment to PR'
        required: false
        default: false
        type: boolean

jobs:
  cleanup-dev-files:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove dev files
        run: |
          echo "Cleaning up dev files from ${{ github.event.pull_request.base.ref }} branch..."

          # COMPREHENSIVE Dev Files Cleanup - Safe to commit to feature branches, must be cleaned from production branches
          files_to_remove=(
            # AI Development Tools & Context
            ".claude"
            ".claude/"
            "CLAUDE.md"
            ".mcp.json"
            ".taskmaster"
            ".taskmaster/"
            ".cursor"
            ".cursor/"
            ".aider*"
            "ai_docs"
            "ai_docs/"
            
            # Python Development Artifacts
            "__pycache__"
            "__pycache__/"
            "*.pyc"
            "*.pyo"
            "*.pyd"
            ".pytest_cache"
            ".pytest_cache/"
            "htmlcov"
            "htmlcov/"
            "coverage.xml"
            "coverage.json"
            ".coverage"
            ".coverage.*"
            "pytest-report.json"
            ".mypy_cache"
            ".mypy_cache/"
            ".ruff_cache"
            ".ruff_cache/"
            
            # Build & Distribution
            "build/"
            "dist/"
            "*.egg-info"
            "*.egg-info/"
            ".tox/"
            ".nox/"
            
            # Development Directories
            "artifacts"
            "artifacts/"
            "logs"
            "logs/"
            "dev-outputs"
            "dev-outputs/"
            "tmp"
            "tmp/"
            "debug"
            "debug/"
            ".cache"
            ".cache/"
            
            # Editor & IDE Files
            ".vscode/settings.json"
            ".idea"
            ".idea/"
            "*.code-workspace"
            ".spyderproject"
            ".spyproject"
            ".ropeproject"
            
            # Temporary & OS Files
            "*.dev"
            "*.tmp"
            "*.temp"
            "*.swp"
            "*.swo"
            "*~"
            ".DS_Store"
            "Thumbs.db"
            "Thumbs.db:encryptable"
            "ehthumbs.db"
            "ehthumbs_vista.db"
            "Desktop.ini"
            "$RECYCLE.BIN/"
            "*.stackdump"
            
            # Security & Environment
            ".env.local"
            ".env.*.local"
            "secrets.json"
            ".secrets.baseline"
            
            # Performance & Profiling
            "performance_data"
            "performance_data/"
            ".prof"
            "*.prof"
            
            # Package Manager Artifacts
            "node_modules/"
            "package-lock.json"
            "yarn.lock"
            ".pixi/envs"
            
            # Backup Files
            "*.bak"
            "*.backup"
            "*.orig"
          )

          # Add additional patterns if provided
          if [[ -n "${{ inputs.additional_patterns }}" ]]; then
            IFS=',' read -ra ADDITIONAL <<< "${{ inputs.additional_patterns }}"
            for pattern in "${ADDITIONAL[@]}"; do
              files_to_remove+=("$(echo "$pattern" | xargs)")
            done
          fi

          removed_files=()

          for pattern in "${files_to_remove[@]}"; do
            if [[ "$pattern" == *"*"* ]]; then
              # Handle patterns with wildcards
              for file in $pattern; do
                if [[ -e "$file" ]]; then
                  echo "Removing: $file"
                  rm -rf "$file"
                  removed_files+=("$file")
                fi
              done
            else
              # Handle exact file/directory names
              if [[ -e "$pattern" ]]; then
                echo "Removing: $pattern"
                rm -rf "$pattern"
                removed_files+=("$pattern")
              fi
            fi
          done

          # Log what was removed
          if [ ${#removed_files[@]} -gt 0 ]; then
            echo "Removed files/directories:"
            printf '%s\n' "${removed_files[@]}"
          else
            echo "No dev files found to remove"
          fi

      - name: Commit cleanup if files were removed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are any changes
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "chore: comprehensive cleanup of development artifacts after PR merge

            Automatically removed development files that shouldn't be in production branches:
            
            🤖 AI Development Tools:
            - CLAUDE.md, .claude/, .mcp.json, .taskmaster/, ai_docs/
            - .cursor/, .aider* (Editor AI configs)
            
            🐍 Python Development Artifacts:
            - __pycache__/, *.pyc, .pytest_cache/, htmlcov/, coverage.xml
            - .mypy_cache/, .ruff_cache/, build/, dist/, *.egg-info/
            
            📁 Development Directories:
            - artifacts/, logs/, performance_data/, tmp/, debug/
            
            🔧 Editor & IDE Files:
            - .vscode/settings.json, .idea/, *.code-workspace
            
            🗃️ Temporary & OS Files:
            - *.tmp, *.dev, .DS_Store, Thumbs.db, *~
            
            This keeps production branches clean while preserving dev context in feature branches.
            
            PR: #${{ github.event.pull_request.number }}
            Source: ${{ github.event.pull_request.head.ref }}"

            git push origin ${{ github.event.pull_request.base.ref }}
            echo "✅ Dev files cleanup committed to ${{ github.event.pull_request.base.ref }}"
          else
            echo "✅ No dev files to cleanup"
          fi

      - name: Add cleanup comment to PR
        if: success() && !inputs.skip_comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: |
                🧹 **Comprehensive Development Artifacts Cleanup Complete**

                The following development files have been automatically removed from the `${{ github.event.pull_request.base.ref }}` branch after merge:

                - 🤖 **AI Development Tools**: CLAUDE.md, .taskmaster/, ai_docs/, .claude/, .mcp.json
                - 🐍 **Python Artifacts**: __pycache__/, coverage files, build artifacts, cache directories  
                - 📁 **Development Directories**: artifacts/, logs/, performance_data/, tmp/
                - 🔧 **Editor Configs**: .vscode/, .idea/, editor-specific files
                - 🗃️ **Temporary Files**: *.tmp, *.dev, OS-specific files

                **Philosophy**: Development files are valuable during feature work and preserved in feature branches, but automatically cleaned from production branches to maintain repository hygiene.

                *This methodology allows relaxed development practices while ensuring clean production branches.*
            })
