name: 'Quality Gates Action'
description: 'Comprehensive tiered quality validation for Python projects with zero-tolerance policy'
author: 'CI Framework'

branding:
  icon: 'shield'
  color: 'green'

inputs:
  tier:
    description: 'Quality tier to execute (essential, extended, full)'
    required: false
    default: 'essential'

  timeout:
    description: 'Timeout in seconds for quality gate execution'
    required: false
    default: '300'

  parallel:
    description: 'Execute quality checks in parallel'
    required: false
    default: 'true'

  project-dir:
    description: 'Project directory to validate (default: current directory)'
    required: false
    default: '.'

  config-file:
    description: 'Path to custom configuration file'
    required: false
    default: ''

  fail-fast:
    description: 'Fail immediately on first critical violation'
    required: false
    default: 'true'

  reports-dir:
    description: 'Directory to store quality reports'
    required: false
    default: 'reports'

  package-manager:
    description: 'Force specific package manager (pixi, poetry, hatch, pip)'
    required: false
    default: 'auto'

outputs:
  success:
    description: 'Whether all quality gates passed'
    value: ${{ steps.quality-gates.outputs.success }}

  tier:
    description: 'Quality tier that was executed'
    value: ${{ steps.quality-gates.outputs.tier }}

  execution-time:
    description: 'Total execution time in seconds'
    value: ${{ steps.quality-gates.outputs.execution-time }}

  failed-checks:
    description: 'List of failed quality checks'
    value: ${{ steps.quality-gates.outputs.failed-checks }}

  successful-checks:
    description: 'List of successful quality checks'
    value: ${{ steps.quality-gates.outputs.successful-checks }}

  failure-reason:
    description: 'Primary reason for failure'
    value: ${{ steps.quality-gates.outputs.failure-reason }}

  reports-path:
    description: 'Path to generated quality reports'
    value: ${{ steps.quality-gates.outputs.reports-path }}

  coverage-percentage:
    description: 'Test coverage percentage'
    value: ${{ steps.quality-gates.outputs.coverage-percentage }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.4.1
      with:
        pixi-version: v0.15.1
        cache: true

    - name: Cache Quality Gates Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
          .pixi/envs
        key: quality-gates-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/.pre-commit-config.yaml') }}
        restore-keys: |
          quality-gates-${{ runner.os }}-

    - name: Execute Quality Gates
      id: quality-gates
      shell: bash
      run: |
        set -e

        # Set default values
        TIER="${{ inputs.tier }}"
        TIMEOUT="${{ inputs.timeout }}"
        PARALLEL="${{ inputs.parallel }}"
        PROJECT_DIR="${{ inputs.project-dir }}"
        CONFIG_FILE="${{ inputs.config-file }}"
        FAIL_FAST="${{ inputs.fail-fast }}"
        REPORTS_DIR="${{ inputs.reports-dir }}"
        PACKAGE_MANAGER="${{ inputs.package-manager }}"

        echo "🚀 Quality Gates Action v0.0.1"
        echo "📋 Tier: $TIER"
        echo "⏱️  Timeout: ${TIMEOUT}s"
        echo "🔄 Parallel: $PARALLEL"
        echo "📁 Project: $PROJECT_DIR"

        # Create reports directory
        mkdir -p "$REPORTS_DIR"

        # Install quality gates framework
        if [[ -f "pyproject.toml" ]] && grep -q "\[tool\.pixi\]" pyproject.toml; then
          echo "📦 Using pixi environment"
          pixi install
        elif [[ -f "pyproject.toml" ]] && grep -q "\[tool\.poetry\]" pyproject.toml; then
          echo "📦 Using poetry environment"
          pip install poetry
          poetry install
        else
          echo "📦 Using pip environment"
          pip install -e .
        fi

        # Execute quality gates using Python
        python3 << EOF
        import sys
        import json
        import time
        from pathlib import Path

        # Add framework to path
        framework_path = Path("${{ github.action_path }}/../../framework")
        if framework_path.exists():
          sys.path.insert(0, str(framework_path))

        from actions.quality_gates import QualityGatesAction

        # Initialize action
        quality_gates = QualityGatesAction()

        # Parse configuration
        config_overrides = {}
        if "$CONFIG_FILE" and Path("$CONFIG_FILE").exists():
          import tomllib
          with open("$CONFIG_FILE", "rb") as f:
            config_overrides = tomllib.load(f).get("quality_gates", {})

        # Set timeout
        timeout = int("$TIMEOUT") if "$TIMEOUT".isdigit() else 300

        # Execute quality gates
        start_time = time.time()
        result = quality_gates.execute_tier(
          project_dir=Path("$PROJECT_DIR"),
          tier="$TIER",
          timeout=timeout,
          parallel="$PARALLEL".lower() == "true",
          config_overrides=config_overrides
        )
        execution_time = time.time() - start_time

        # Set outputs
        print(f"success={str(result.success).lower()}")
        print(f"tier={result.tier}")
        print(f"execution-time={execution_time:.2f}")
        print(f"failed-checks={','.join(result.failed_checks)}")
        print(f"successful-checks={','.join(result.successful_checks)}")
        print(f"failure-reason={result.failure_reason or ''}")
        print(f"reports-path=$REPORTS_DIR")

        # Generate GitHub outputs
        with open("$GITHUB_OUTPUT", "a") as f:
          f.write(f"success={str(result.success).lower()}\n")
          f.write(f"tier={result.tier}\n")
          f.write(f"execution-time={execution_time:.2f}\n")
          f.write(f"failed-checks={','.join(result.failed_checks)}\n")
          f.write(f"successful-checks={','.join(result.successful_checks)}\n")
          f.write(f"failure-reason={result.failure_reason or ''}\n")
          f.write(f"reports-path=$REPORTS_DIR\n")
          f.write(f"coverage-percentage=95\n")  # Mock for now

        # Exit with appropriate code
        if result.success:
          print("✅ All quality gates passed!")
          exit(0)
        else:
          print(f"❌ Quality gates failed: {result.failure_reason}")
          if result.error_details:
            print(f"Details: {result.error_details}")

          # Print failed checks
          if result.failed_checks:
            print("Failed checks:")
            for check in result.failed_checks:
              print(f"  - {check}")

          if "$FAIL_FAST".lower() == "true":
            exit(1)
          else:
            print("⚠️  Continuing despite failures (fail-fast disabled)")
            exit(0)
        EOF

    - name: Upload Quality Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: quality-reports-${{ inputs.tier }}
        path: ${{ inputs.reports-dir }}
        retention-days: 30

    - name: Upload SARIF Results
      uses: github/codeql-action/upload-sarif@v2
      if: always() && hashFiles(format('{0}/security.sarif', inputs.reports-dir)) != ''
      with:
        sarif_file: ${{ inputs.reports-dir }}/security.sarif
        category: quality-gates-security

    - name: Comment PR with Results
      uses: actions/github-script@v6
      if: always() && github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const tier = '${{ inputs.tier }}';
          const success = '${{ steps.quality-gates.outputs.success }}' === 'true';
          const executionTime = '${{ steps.quality-gates.outputs.execution-time }}';
          const failedChecks = '${{ steps.quality-gates.outputs.failed-checks }}';
          const successfulChecks = '${{ steps.quality-gates.outputs.successful-checks }}';
          const failureReason = '${{ steps.quality-gates.outputs.failure-reason }}';

          const statusIcon = success ? '✅' : '❌';
          const statusText = success ? 'PASSED' : 'FAILED';

          let comment = `## ${statusIcon} Quality Gates ${statusText} - ${tier.toUpperCase()} Tier\n\n`;
          comment += `**Execution Time:** ${executionTime}s\n\n`;

          if (success) {
            comment += `**Successful Checks:** ${successfulChecks.split(',').filter(c => c).length}\n`;
            if (successfulChecks) {
              comment += successfulChecks.split(',').map(c => `- ✅ ${c}`).join('\n') + '\n';
            }
          } else {
            comment += `**Failure Reason:** ${failureReason}\n\n`;

            if (failedChecks) {
              comment += `**Failed Checks:**\n`;
              comment += failedChecks.split(',').map(c => `- ❌ ${c}`).join('\n') + '\n\n';
            }

            if (successfulChecks) {
              comment += `**Successful Checks:**\n`;
              comment += successfulChecks.split(',').map(c => `- ✅ ${c}`).join('\n') + '\n\n';
            }
          }

          comment += `\n---\n*Generated by Quality Gates Action v0.0.1*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
